services:
  php-apache:
    container_name: php-apache
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: felix
      MYSQL_DATABASE: app_db
      MYSQL_USER: marc
      MYSQL_PASSWORD: felix
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
